### ISSUE TITLE
PH3. Document Review

### ISSUE THREAD

**Issue by rslruiz** [Simbajon/oo3CyborgProject#3]
1. Readme: Needs improvement
   - Improve formatting (make the description more visible).
   - Do not include the progress updates on the README.md
   - Aside from the description. Include and enumerate the features of the program.
2. Project Proposal: Developing

   - Missing UML and Evaluation
   - Include the references in the document
   - Aside from the gantt chart, include what each member will be doing during the specific dates.
   - In the methodology, discuss how Object Oriented Principles and Design will be applied to your project.
3. IPO: Complete
4. Flowchart: Complete
5. Class Diagram: None
6. Java codes: None

**Comment by Simbajon** [comment]
Done po!
